Removed Commented code lines
tillioss/tilli-web-app pull request #87
Opened 2023-10-04 17:56 UTC by hparihar-07

Fixed#80 by removing all the commented code lines

2023-10-05 04:00 UTC, anjula-sack commented
@hparihar-07 Please always make sure an issue is assigned for you before making a pull request. Don't make PRs for the issues that you are not assigned. Always drop a comment on the issue mentioning that you are interested at least.

2023-10-05 05:39 UTC, hparihar-07 commented
Sorry for that I found that no one was replying

2023-10-05 07:08 UTC, anjula-sack commented
> Sorry for that I found that no one was replying

No worries :)

2023-10-05 14:48 UTC, anjula-sack requested changes
Remove this console log as well,

https://github.com/tillioss/tilli-web-app/blob/3a3401ac6ce8902d8466dba46322a219bb3bd99f/src/pages/TrackProgressScreen.js#L81

2023-10-05 16:24 UTC, hparihar-07 commented
> Remove this console log as well,
> 
> https://github.com/tillioss/tilli-web-app/blob/3a3401ac6ce8902d8466dba46322a219bb3bd99f/src/pages/TrackProgressScreen.js#L81

Ok sir

2023-10-06 00:58 UTC, anjula-sack approved these changes
Please remove the mentioned empty lines as well

2023-10-06 00:58 UTC, anjula-sack commented on src/pages/TrackProgressScreen.js
> +
```suggestion           
```

2023-10-06 00:58 UTC, anjula-sack commented on src/pages/TrackProgressScreen.js
> +
```suggestion
```

2023-10-06 00:58 UTC, anjula-sack commented on src/pages/TrackProgressScreen.js
> +
```suggestion
```

2023-10-07 04:42 UTC, merged